In [1]:
# import lib
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt 
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
data = pd.read_csv('../data/proceed/Clean_data.csv')

In [5]:
data.head()

,accounting_date,company_code,customer_code,customer_district_code,item_code,business_chain_l1_name,salesperson_code,market_segment,value_sales,value_cost,...,business_chain_l1_code_ZZ1,business_chain_l1_code_ZZ2,contact_method_code_Other,order_type_code_NOR,order_type_code_Other,Profit,Unit_Price,Profit_Margin,Transformed_Profit,Transformed_Unit_Price
0,2012-05-09,101,411800601,410,GENIE8WWWBC,ElectraCorp Ltd,T612,Commercial & Industrial,218.40,178.1976,...,False,False,False,True,False,40.2024,2.60,18.407692,6.340536,1.280934
1,2012-02-16,101,361000403,300,GENIE8WWWBC,BrightPower Solutions,P345,Commercial & Industrial,38.28,25.4568,...,False,False,False,True,False,12.8232,3.19,33.498433,3.580950,1.432701
2,2012-05-09,101,361000403,300,GENIE8WWWBC,BrightPower Solutions,P345,Commercial & Industrial,40.20,25.4568,...,False,False,False,True,False,14.7432,3.35,36.674627,3.839687,1.470176
3,2012-05-18,101,565540415,500,GENIE8WWWBC,Global Electric Wholesalers,T504,Commercial & Industrial,20.10,12.7284,...,False,False,False,False,False,7.3716,3.35,36.674627,2.715069,1.470176
4,2012-01-09,101,565540415,500,GENIE8WWWBC,Global Electric Wholesalers,T504,Commercial & Industrial,19.14,12.7284,...,False,False,False,False,False,6.4116,3.19,33.498433,2.532114,1.432701

1. Question 1: What factors impact sales revenue in different market segments?
Selected Variables

Dependent Variable: value_sales
Independent Variables:
value_quantity: Quantity of items sold
market_segment: Market segment (categorical variable)
value_price_adjustment: Adjustment in price
day_gap: The gap in days between certain events (if relevant to timing effects)
light_source_LED and light_source_Traditional: Type of light source (already one-hot encoded)

1. Question 2: How does profit margin correlate with operational factors like product type, cost, and sales quantity?
Objective: To determine the key drivers of profit margin, helping LuminaTech identify products or regions that contribute most to profitability.

Dependent Variable: profit_margin

In [15]:
# Display the column names
data.columns

Index(['accounting_date', 'company_code', 'customer_code',
       'customer_district_code', 'item_code', 'business_chain_l1_name',
       'salesperson_code', 'market_segment', 'value_sales', 'value_cost',
       'value_quantity', 'value_price_adjustment', 'currency',
       'invoice_number', 'line_number', 'invoice_date',
       'customer_order_number', 'order_date', 'dss_update_time', 'day_gap',
       'order_group', 'value_sales_log_plus1_transformed',
       'value_cost_log_plus1_transformed',
       'value_quantity_log_plus1_transformed', 'business_area_code_DLT',
       'business_area_code_LMP', 'business_area_code_OTH',
       'business_area_code_Other', 'business_area_code_SUR',
       'item_group_code_Other', 'item_class_code_LMP01',
       'item_class_code_LMP03', 'item_class_code_LMP04',
       'item_class_code_LMP05', 'item_class_code_Other', 'item_type_5',
       'item_type_6', 'item_type_7', 'item_type_Other',
       'bonus_group_code_Trade', 'environment_group_code_Other',
       'environment_group_code_P', 'environment_group_code_R',
       'environment_group_code_S', 'technology_group_code_76',
       'technology_group_code_78', 'technology_group_code_86',
       'technology_group_code_90', 'technology_group_code_CROM',
       'technology_group_code_NA', 'technology_group_code_Other',
       'technology_group_code_PIER', 'technology_group_code_SYLV',
       'commission_group_code_Other', 'reporting_classification_Discontinuing',
       'light_source_LED', 'light_source_Traditional', 'warehouse_code_5V0',
       'warehouse_code_CN0', 'warehouse_code_Other', 'warehouse_code_Unk',
       'abc_class_code_B', 'abc_class_code_C', 'abc_class_code_D',
       'abc_class_code_G', 'abc_class_code_J', 'abc_class_code_Other',
       'abc_class_code_U', 'abc_class_volume_J', 'abc_class_volume_Other',
       'abc_class_volume_U', 'business_chain_l1_code_ELC',
       'business_chain_l1_code_MED', 'business_chain_l1_code_NES',
       'business_chain_l1_code_Other', 'business_chain_l1_code_ZZ1',
       'business_chain_l1_code_ZZ2', 'contact_method_code_Other',
       'order_type_code_NOR', 'order_type_code_Other', 'Profit', 'Unit_Price',
       'Profit_Margin', 'Transformed_Profit', 'Transformed_Unit_Price'],
      dtype='object')

In [26]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1971500 entries, 0 to 1971499
Data columns (total 85 columns):
 #   Column                                  Dtype
---  ------                                  -----
 0   accounting_date                         object
 1   company_code                            int64
 2   customer_code                           object
 3   customer_district_code                  int64
 4   item_code                               object
 5   business_chain_l1_name                  object
 6   salesperson_code                        object
 7   market_segment                          object
 8   value_sales                             float64
 9   value_cost                              float64
 10  value_quantity                          float64
 11  value_price_adjustment                  int64
 12  currency                                object
 13  invoice_number                          int64
 14  line_number                             int64
 15  invoice_date                            object
 16  customer_order_number                   object
 17  order_date                              object
 18  dss_update_time                         object
 19  day_gap                                 int64
 20  order_group                             object
 21  value_sales_log_plus1_transformed       float64
 22  value_cost_log_plus1_transformed        float64
 23  value_quantity_log_plus1_transformed    float64
 24  business_area_code_DLT                  bool
 25  business_area_code_LMP                  bool
 26  business_area_code_OTH                  bool
 27  business_area_code_Other                bool
 28  business_area_code_SUR                  bool
 29  item_group_code_Other                   bool
 30  item_class_code_LMP01                   bool
 31  item_class_code_LMP03                   bool
 32  item_class_code_LMP04                   bool
 33  item_class_code_LMP05                   bool
 34  item_class_code_Other                   bool
 35  item_type_5                             bool
 36  item_type_6                             bool
 37  item_type_7                             bool
 38  item_type_Other                         bool
 39  bonus_group_code_Trade                  bool
 40  environment_group_code_Other            bool
 41  environment_group_code_P                bool
 42  environment_group_code_R                bool
 43  environment_group_code_S                bool
 44  technology_group_code_76                bool
 45  technology_group_code_78                bool
 46  technology_group_code_86                bool
 47  technology_group_code_90                bool
 48  technology_group_code_CROM              bool
 49  technology_group_code_NA                bool
 50  technology_group_code_Other             bool
 51  technology_group_code_PIER              bool
 52  technology_group_code_SYLV              bool
 53  commission_group_code_Other             bool
 54  reporting_classification_Discontinuing  bool
 55  light_source_LED                        bool
 56  light_source_Traditional                bool
 57  warehouse_code_5V0                      bool
 58  warehouse_code_CN0                      bool
 59  warehouse_code_Other                    bool
 60  warehouse_code_Unk                      bool
 61  abc_class_code_B                        bool
 62  abc_class_code_C                        bool
 63  abc_class_code_D                        bool
 64  abc_class_code_G                        bool
 65  abc_class_code_J                        bool
 66  abc_class_code_Other                    bool
 67  abc_class_code_U                        bool
 68  abc_class_volume_J                      bool
 69  abc_class_volume_Other                  bool
 70  abc_class_volume_U                      bool
 71  business_chain_l1_code_ELC              bool
 72  business_chain_l1_code_MED              bool
 73  business_chain_l1_code_NES              bool
 74  business_chain_l1_code_Other            bool
 75  business_chain_l1_code_ZZ1              bool
 76  business_chain_l1_code_ZZ2              bool
 77  contact_method_code_Other               bool
 78  order_type_code_NOR                     bool
 79  order_type_code_Other                   bool
 80  Profit                                  float64
 81  Unit_Price                              float64
 82  Profit_Margin                           float64
 83  Transformed_Profit                      float64
 84  Transformed_Unit_Price                  float64
dtypes: bool(56), float64(11), int64(6), object(12)
memory usage: 541.5+ MB

In [34]:
# Filter only numeric and boolean columns for correlation calculation
data_numeric = data.select_dtypes(include=['number', 'bool'])

# Calculate the correlation matrix
corr_matrix = data_numeric.corr()

# Show correlations with 'value_sales', sorted by absolute value in descending order
top_10_corr_with_sales = corr_matrix['value_sales'].abs().sort_values(ascending=False).head(10)
print(top_10_corr_with_sales)

value_sales                          1.000000
value_cost                           0.949025
Profit                               0.804550
Transformed_Profit                   0.636567
Unit_Price                           0.243199
value_sales_log_plus1_transformed    0.224283
Transformed_Unit_Price               0.203826
value_quantity                       0.185489
bonus_group_code_Trade               0.165260
value_cost_log_plus1_transformed     0.145786
Name: value_sales, dtype: float64